import * as yup from "yup";

export const profileSchema = yup.object().shape({
  firstName: yup.string().required("First name is required"),
  lastName: yup.string().required("Last name is required"),
  userName: yup.string().required("User name is required"),
  displayName: yup.string().required("Display name is required"),
  nativeLanguage: yup.string().required("Native language is required"),
  otherLanguages: yup.array().of(yup.string()),
  phone: yup.string().required("Phone is required"),
  additionalPhone: yup.string(),
  email: yup.string().email().required("Email is required"),
  additionalEmail: yup.string().email(),
  bio: yup.string(),
  streetAddress: yup.string(),
  apartment: yup.string(),
  city: yup.string(),
  state: yup.string(),
  postalCode: yup.string(),
  area: yup.string(),
  country: yup.string(),
  emergencyName: yup.string(),
  emergencyRelationship: yup.string(),
  emergencyEmail: yup.string().email(),
  emergencyPhone: yup.string(),
  facebook: yup.string().url(),
  instagram: yup.string().url(),
  airbnb: yup.string().url(),
  vrbo: yup.string().url(),
  youtube: yup.string().url(),
  twitter: yup.string().url(),
  linkedin: yup.string().url(),
  pinterest: yup.string().url(),
  vimeo: yup.string().url(),
  tripadvisor: yup.string().url(),
}); 